name: rocket-equation
version: 0.1.0.0
github: "Manfred/rocket-equation"
license: MIT
author: "Manfred Stienstra"
maintainer: "manfred@fngtps.com"
copyright: "Manfred Stienstra"

extra-source-files:
- README.md

description: Pew pew rockets in space.

dependencies:
- base == 4.*

library:
  source-dirs: src

executables:
  rocket-equation-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rocket-equation

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: rocket-equation
